export const mockPodcasts = [
  {
    'im:name': { label: 'Podcast 1' },
    'im:image': [
      { label: 'image11.jpg', attributes: { height: '600' } },
      { label: 'image21.jpg', attributes: { height: '600' } },
      { label: 'image31.jpg', attributes: { height: '600' } },
    ],
    summary: { label: 'This is Podcast 1' },
    id: { label: 'url1', attributes: { 'im:id': '1' } },
    'im:artist': { label: 'Artist 1', attributes: { href: 'artist1.com' } },
    'im:price': {
      label: 'Free',
      attributes: { amount: '0.00', currency: 'USD' },
    },
    'im:contentType': { attributes: { term: 'Podcast', label: 'Audio' } },
    rights: { label: 'All rights reserved' },
    title: { label: 'Podcast 1' },
    link: {
      attributes: {
        rel: 'alternate',
        type: 'text/html',
        href: 'http://example.com/1',
      },
    },
    category: {
      attributes: {
        'im:id': '1',
        term: 'Education',
        scheme: 'https://example.com',
        label: 'Education',
      },
    },
    'im:releaseDate': {
      label: '2022-01-01T00:00:00Z',
      attributes: { label: 'January 1, 2022' },
    },
  },
  {
    'im:name': { label: 'Podcast 2' },
    'im:image': [
      { label: 'image12.jpg', attributes: { height: '600' } },
      { label: 'image22.jpg', attributes: { height: '600' } },
      { label: 'image23.jpg', attributes: { height: '600' } },
    ],
    summary: { label: 'This is Podcast 2' },
    id: { label: 'url2', attributes: { 'im:id': '2' } },
    'im:artist': { label: 'Artist 2', attributes: { href: 'artist2.com' } },
    'im:price': {
      label: 'Free',
      attributes: { amount: '0.00', currency: 'USD' },
    },
    'im:contentType': { attributes: { term: 'Podcast', label: 'Audio' } },
    rights: { label: 'All rights reserved' },
    title: { label: 'Podcast 2' },
    link: {
      attributes: {
        rel: 'alternate',
        type: 'text/html',
        href: 'http://example.com/2',
      },
    },
    category: {
      attributes: {
        'im:id': '2',
        term: 'Business',
        scheme: 'https://example.com',
        label: 'Business',
      },
    },
    'im:releaseDate': {
      label: '2022-02-01T00:00:00Z',
      attributes: { label: 'February 1, 2022' },
    },
  },
  {
    'im:name': { label: 'Podcast 3' },
    'im:image': [
      { label: 'image13.jpg', attributes: { height: '600' } },
      { label: 'image23.jpg', attributes: { height: '600' } },
      { label: 'image33.jpg', attributes: { height: '600' } },
    ],
    summary: { label: 'This is Podcast 3' },
    id: { label: 'url3', attributes: { 'im:id': '3' } },
    'im:artist': { label: 'Artist 3', attributes: { href: 'artist3.com' } },
    'im:price': {
      label: 'Free',
      attributes: { amount: '0.00', currency: 'USD' },
    },
    'im:contentType': { attributes: { term: 'Podcast', label: 'Audio' } },
    rights: { label: 'All rights reserved' },
    title: { label: 'Podcast 3' },
    link: {
      attributes: {
        rel: 'alternate',
        type: 'text/html',
        href: 'http://example.com/3',
      },
    },
    category: {
      attributes: {
        'im:id': '3',
        term: 'Technology',
        scheme: 'https://example.com',
        label: 'Technology',
      },
    },
    'im:releaseDate': {
      label: '2022-03-01T00:00:00Z',
      attributes: { label: 'March 1, 2022' },
    },
  },
];

export const mockPodcastDetail = [
  {
    artistId: 1,
    artistName: 'Artist 1',
    artistViewUrl: 'artist1.com',
    artworkUrl30: 'image1_30.jpg',
    artworkUrl60: 'image1_60.jpg',
    artworkUrl100: 'image1_100.jpg',
    artworkUrl600: 'image1_600.jpg',
    collectionCensoredName: 'Podcast 1',
    collectionExplicitness: 'Clean',
    collectionHdPrice: 0,
    collectionId: 1,
    collectionName: 'Podcast 1',
    collectionPrice: 0,
    collectionViewUrl: 'url1',
    country: 'US',
    currency: 'USD',
    feedUrl: 'url1',
    genreIds: ['1'],
    genres: ['Education'],
    kind: 'podcast',
    primaryGenreName: 'Education',
    releaseDate: '2022-01-01T00:00:00Z',
    trackCensoredName: 'Podcast 1',
    trackCount: 10,
    trackExplicitness: 'Clean',
    trackId: 1,
    trackName: 'Podcast 1',
    trackPrice: 0,
    trackTimeMillis: 3600000,
    trackViewUrl: 'url1',
    wrapperType: 'collection',
  },
  {
    artistId: 2,
    artistName: 'Artist 2',
    artistViewUrl: 'artist2.com',
    artworkUrl30: 'image2_30.jpg',
    artworkUrl60: 'image2_60.jpg',
    artworkUrl100: 'image2_100.jpg',
    artworkUrl600: 'image2_600.jpg',
    collectionCensoredName: 'Podcast 2',
    collectionExplicitness: 'Clean',
    collectionHdPrice: 0,
    collectionId: 2,
    collectionName: 'Podcast 2',
    collectionPrice: 0,
    collectionViewUrl: 'url2',
    country: 'US',
    currency: 'USD',
    feedUrl: 'url2',
    genreIds: ['2'],
    genres: ['Education'],
    kind: 'podcast',
    primaryGenreName: 'Education',
    releaseDate: '2022-01-02T00:00:00Z',
    trackCensoredName: 'Podcast 2',
    trackCount: 10,
    trackExplicitness: 'Clean',
    trackId: 2,
    trackName: 'Podcast 2',
    trackPrice: 0,
    trackTimeMillis: 3600000,
    trackViewUrl: 'url2',
    wrapperType: 'collection',
  },
  {
    artistId: 3,
    artistName: 'Artist 3',
    artistViewUrl: 'artist3.com',
    artworkUrl30: 'image3_30.jpg',
    artworkUrl60: 'image3_60.jpg',
    artworkUrl100: 'image3_100.jpg',
    artworkUrl600: 'image3_600.jpg',
    collectionCensoredName: 'Podcast 3',
    collectionExplicitness: 'Clean',
    collectionHdPrice: 0,
    collectionId: 3,
    collectionName: 'Podcast 3',
    collectionPrice: 0,
    collectionViewUrl: 'url3',
    country: 'US',
    currency: 'USD',
    feedUrl: 'url3',
    genreIds: ['3'],
    genres: ['Education'],
    kind: 'podcast',
    primaryGenreName: 'Education',
    releaseDate: '2022-01-03T00:00:00Z',
    trackCensoredName: 'Podcast 3',
    trackCount: 10,
    trackExplicitness: 'Clean',
    trackId: 3,
    trackName: 'Podcast 3',
    trackPrice: 0,
    trackTimeMillis: 3600000,
    trackViewUrl: 'url3',
    wrapperType: 'collection',
  },
];

export const mockEpisodes = [
  {
    artistIds: [1],
    artistViewUrl: 'artist1.com',
    artworkUrl60: 'image1_60.jpg',
    artworkUrl160: 'image1_160.jpg',
    artworkUrl600: 'image1_600.jpg',
    closedCaptioning: 'CC',
    collectionId: 1,
    collectionName: 'Podcast 1',
    collectionViewUrl: 'url1',
    contentAdvisoryRating: 'Clean',
    country: 'US',
    description: 'This is Episode 1 of Podcast 1.',
    episodeContentType: 'audio',
    episodeFileExtension: '.mp3',
    episodeGuid: '1',
    episodeUrl: 'https://podcast1.com/episodes/1.mp3',
    feedUrl: 'url1',
    genres: [{ name: 'Education', id: '1' }],
    kind: 'episode',
    previewUrl: 'https://podcast1.com/episodes/1.mp3',
    releaseDate: '2022-01-01T00:00:00Z',
    shortDescription: 'This is Episode 1 of Podcast 1.',
    trackId: 1,
    trackName: 'Episode 1',
    trackTimeMillis: 3600000,
    trackViewUrl: 'https://podcast1.com/episodes/1',
    wrapperType: 'track',
  },
  {
    artistIds: [2],
    artistViewUrl: 'artist2.com',
    artworkUrl60: 'image2_60.jpg',
    artworkUrl160: 'image2_160.jpg',
    artworkUrl600: 'image2_600.jpg',
    closedCaptioning: 'CC',
    collectionId: 2,
    collectionName: 'Podcast 2',
    collectionViewUrl: 'url2',
    contentAdvisoryRating: 'Clean',
    country: 'US',
    description: 'This is Episode 2 of Podcast 1.',
    episodeContentType: 'audio',
    episodeFileExtension: '.mp3',
    episodeGuid: '2',
    episodeUrl: 'https://podcast2.com/episodes/1.mp3',
    feedUrl: 'url2',
    genres: [{ name: 'Education', id: '2' }],
    kind: 'episode',
    previewUrl: 'https://podcast2.com/episodes/1.mp3',
    releaseDate: '2022-01-02T00:00:00Z',
    shortDescription: 'This is Episode 2 of Podcast 1.',
    trackId: 2,
    trackName: 'Episode 2',
    trackTimeMillis: 3600000,
    trackViewUrl: 'https://podcast2.com/episodes/1',
    wrapperType: 'track',
  },
  {
    artistIds: [3],
    artistViewUrl: 'artist3.com',
    artworkUrl60: 'image3_60.jpg',
    artworkUrl160: 'image3_160.jpg',
    artworkUrl600: 'image3_600.jpg',
    closedCaptioning: 'CC',
    collectionId: 3,
    collectionName: 'Podcast 3',
    collectionViewUrl: 'url3',
    contentAdvisoryRating: 'Clean',
    country: 'US',
    description: 'This is Episode 3 of Podcast 1.',
    episodeContentType: 'audio',
    episodeFileExtension: '.mp3',
    episodeGuid: '3',
    episodeUrl: 'https://podcast3.com/episodes/1.mp3',
    feedUrl: 'url3',
    genres: [{ name: 'Education', id: '3' }],
    kind: 'episode',
    previewUrl: 'https://podcast3.com/episodes/1.mp3',
    releaseDate: '2022-01-03T00:00:00Z',
    shortDescription: 'This is Episode 3 of Podcast 1.',
    trackId: 3,
    trackName: 'Episode 3',
    trackTimeMillis: 3600000,
    trackViewUrl: 'https://podcast3.com/episodes/1',
    wrapperType: 'track',
  },
];
